services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mergeleague
      POSTGRES_PASSWORD: mergeleague
      POSTGRES_DB: mergeleague
    volumes:
      - mergeleague_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mergeleague_pg:
